server:
  port: 9095
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_HOST:http://localhost:9098/eureka/}
  instance:
    instance-id: food-backend-instance-1
spring:
  application:
    name: backend
  datasource:
    url: jdbc:postgresql://localhost:5432/food_1
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate